-- V001: Создание исходных таблиц

-- Таблица с продуктами (сосисками)
CREATE TABLE product(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    name varchar(255) not null, 
    picture_url varchar(255)
);

-- Таблица с дополнительной информацией о продуктах
CREATE TABLE product_info(
    product_id bigint not null, 
    name varchar(255) not null, 
    price double precision
);

-- Таблица с заказами
CREATE TABLE orders(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    status varchar(255)
);

-- Таблица с датами заказов
CREATE TABLE orders_date(
    order_id bigint not null, 
    status varchar(255), 
    date_created date default CURRENT_DATE
);

-- Таблица связи заказов и продуктов
CREATE TABLE order_product(
    quantity integer not null, 
    order_id bigint not null, 
    product_id bigint not null
);
