-- V001: Создание исходных таблиц для сосисочной

-- Таблица с продуктами (сосисками)
CREATE TABLE product(
    id bigint generated by default as identity, 
    name varchar(255) not null, 
    picture_url varchar(255)
);

-- Таблица с дополнительной информацией о продуктах
CREATE TABLE product_info(
    product_id bigint not null, 
    name varchar(255) not null, 
    price double precision
);

-- Таблица с заказами
CREATE TABLE orders(
    id bigint generated by default as identity, 
    status varchar(255)
);

-- Таблица с датами заказов
CREATE TABLE orders_date(
    order_id bigint not null, 
    status varchar(255), 
    date_created date default current_date
);

-- Таблица связи заказов и продуктов (что в каком заказе)
CREATE TABLE order_product(
    quantity integer not null, 
    order_id bigint not null, 
    product_id bigint not null
);
