name: Main workflow
on:
  push:
    branches:
      - main
jobs:
  migrate:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: store_default
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Wait for PostgreSQL
      run: |
        for i in {1..30}; do
          if pg_isready -h localhost -p 5432 -U user; then
            echo "PostgreSQL is ready!"
            exit 0
          fi
          sleep 2
        done
        exit 1

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Install Flyway
      run: |
        curl -L -o flyway-commandline.tar.gz "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/11.1.0/flyway-commandline-11.1.0-linux-x64.tar.gz"
        tar -xzf flyway-commandline.tar.gz
        sudo ln -s `pwd`/flyway-11.1.0/flyway /usr/local/bin/flyway

    - name: Run Flyway migrations
      run: |
        flyway migrate \
          -url="jdbc:postgresql://localhost:5432/store_default" \
          -user="user" \
          -password="password" \
          -locations="filesystem:migrations"
